export const PATHS = {
	HOME: '/',
	DASHBOARD: '/dashboard',
	EXPLORE: '/explore',
	DISCOVER: '/community',
	COMMUNITY: '/community',
	MESSAGES: '/messages',
	CREATE: '/create',
	SETTINGS: '/settings',
	AUTH: {
		SIGN_IN: '/auth/sign-in',
		SIGN_UP: '/auth/sign-up',
		VERIFY_OTP: '/auth/verify-otp',
		FORGOT_PASSWORD: '/auth/forgot-password',
		RESET_PASSWORD: '/auth/reset-password',
		GOOGLE_CALLBACK: '/oauth2/callback/google',
	},
	GROUPS: {
		EXPLORE: '/groups',
		MY_GROUPS: '/groups/my',
		DETAIL: (groupId: string) => `/groups/${groupId}`,
		MEMBERS: (groupId: string) => `/groups/${groupId}/members`,
		CREATE: '/groups/create',
		EDIT: (groupId: string) => `/groups/${groupId}/edit`,
	},
}
