import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/components/providers/AuthProvider'
import { GoogleOAuthProvider } from '@react-oauth/google'
import { Topbar } from '@/components/layout/Topbar'
import { LeftSidebar } from '@/components/layout/LeftSidebar'
import { RightSidebar } from '@/components/layout/RightSidebar'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<GoogleOAuthProvider
					clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
				>
					<AuthProvider>
						<div className='grid min-h-screen w-full grid-cols-1 bg-background md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr_300px]'>
							<LeftSidebar />
							<div className='flex flex-col'>
								<Topbar />
								<main className='flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6'>
									{children}
								</main>
							</div>
							<RightSidebar />
						</div>
					</AuthProvider>
				</GoogleOAuthProvider>
			</body>
		</html>
	)
}
